### ISSUE TITLE
Performance hotspot on iOS 9.

### ISSUE THREAD

**Issue by dillan** [facebook/KVOController#72] opened 2015-08-15 00:27 UTC
I'm using KVOController to observe ~12 attributes on 35 objects (so about 420 things being observed in total) and seeing significant performance degradation on iOS 9.

I fired up the time profiler instrument and noticed that inside `-[_FBKVOSharedController observe:info:]` I'm seeing 100% CPU utilization on `[object addObserver:self forKeyPath:info->_keyPath options:info->_options context:(void *)info];`. I'm wondering if anyone else has seen similar behavior on iOS 9. iOS 7 and iOS 8 seem to be around 8x faster.

**Comment by antoinelamy** [comment] 2015-09-14 19:07
We are observing the exact same thing on our end, anyone have an idea of what is going on?

**Comment by grp** [comment] 2015-09-16 09:43
The actual `-addObserver:forKeyPath:options:context:` call is KVO itself, not KVOController — have you checked if you see the same thing without KVOController? If so, might be worth filing as a Radar with Apple...

**Comment by antoinelamy** [comment] 2015-09-16 11:27
We investigated the issue yesterday and it has indeed nothing to do with KVOController but with the iOS 9 changes in KVO implementation. That being said, the performance degradation occurs under some specific circompstances and is more prone to happen with KVOController than without. The order of magnitude of this difference in performance between iOS 8 and iOS 9 is just plain scary and anyone using KVOController extensively in a production app should feel concerned about it.

One of my teammate is in the process of detailing the issue in a radar and is preparing a test project that reproduce the issue using plain KVO. As soon he's done, he will post it here as well so that anyone experiencing the issue can understand what it is about and maybe help finding a workaround until Apple fix it. I would hope found this out earlier before the GM is out but now we have to deal with it.

**Comment by ianolito** [comment] 2015-09-16 12:56
The performance gets worse when many observers are added to a single receiver and when each context value is different. Incidentally, this is exactly how KVOController works: it uses a single receiver `_FBKVOSharedController` and distinct `_FBKVOInfo` objects are used as the context.

The problem seems to come from the new data structure used internally by KVO since iOS 9. Here's a graph that shows the scale of the problem.
![Graph](https://raw.githubusercontent.com/lpios/SlowKVOPerformance/master/Documentation/kvo-performance.png)
(Number of registered observers vs time in ms to register additional observers)

This project reproduces the problem:
https://github.com/lpios/SlowKVOPerformance

**Comment by ianolito** [comment] 2015-09-16 13:37
We filed rdar://22718754

**Comment by dillan** [comment] 2015-09-16 13:46
I've also filed rdar://22718949.

**Comment by Ashton-W** [comment] 2015-09-21 08:25
Could someone explain why we need to route the observation through the shared controller? Could we drop that for iOS 9?

**Comment by ewanmellor** [comment] 2015-10-16 00:09
This is hitting me very hard too.

**Comment by ewanmellor** [comment] 2015-10-17 23:16
I am seeing a very large number of 4K mallocs inside `addObserver:withKeyPath:`.  The run below is for 4100 calls to addObserver, which has turned into 160,000 4K mallocs (!)

<img width="898" alt="screen shot 2015-10-17 at 4 13 49 pm" src="https://cloud.githubusercontent.com/assets/894011/10561683/29dee54e-74ea-11e5-943f-edbec801c25d.png">

**Comment by dillan** [comment] 2015-10-18 02:45
I wanted to share how I've worked around this issue. In my application I've drastically reduced the performance impact by reducing the number of attributes on each object that I am observing. I was able to accomplish this by trading off the granularity of knowing which attribute changed for speed by creating a fake aggregation object. Basically I'm observing an aggregate property on my model class that groups related attributes.

```
@interface MYModelObject : NSObject

@proterty (nonatomic, copy) NSString *string1;
@proterty (nonatomic, copy) NSString *string2;
@proterty (nonatomic, copy) NSString *string3;
@proterty (nonatomic, strong) NSDate date;

@property (readonly) id observationAggregate;

@end

@implementation MYModelObject

+(NSSet *)keyPathsForValuesAffectingObservationAggregate
{
	NSSet *keyPaths = [NSSet setWithObjects:@"string1", @"string2", @"string3", @"date", nil];
	return keyPaths;
}

@end
```

Then my code only observes the aggregate object.

```
[self.KVOController observe:modelObject
                    keyPath:NSStringFromSelector(@selector(observationAggregate))
                    options:(NSKeyValueObservingOptionNew)
                     action:@selector(modelObjectDidChange:object:)];
```

I hope this may help others alleviate this performance regression. In my use case, I refresh the UI whenever the represented model object has a change. With the aggregate object I lose a bit of granularity in these updates since I refresh the the data for each item in the observation aggregate, even if only one of them changed. Please keep this in mind when evaluating the performance trade-off in your own use case.

**Comment by dillan** [comment] 2015-10-18 02:53
FYI, from the reactive cocoa thread on the same issue.

@karmeye commented:
>Apparently many KVO issues was fixed.
>
>But this issue has now been "observed" :) No need to dupe more radars:
>
>https://twitter.com/Catfish_Man/status/644928403402018820
>https://twitter.com/steipete/status/644903661626331141

**Comment by xavierjurado** [comment] 2015-10-22 09:39
It seems this bug is still present on iOS 9.1. I ran the sample project (https://github.com/lpios/SlowKVOPerformance) on my device and saw similar results. With ~1500 iterations:

![screen shot 2015-10-22 at 11 35 41](https://cloud.githubusercontent.com/assets/411994/10661929/4b1cb66c-78b1-11e5-84dc-bc2997b1df24.png)

**Comment by xavierjurado** [comment] 2015-10-22 09:41
The "valley" between iteration ~500 and ~1050 is odd though :confused:

**Comment by karmeye** [comment] 2015-10-22 09:46
Yes, I still see the issue too.

Is that "valley" consistent for each run?

**Comment by xavierjurado** [comment] 2015-10-22 10:07
Nah, I have repeated the experiment but I have not reproduced the same behaviour:

![screen shot 2015-10-22 at 12 04 45](https://cloud.githubusercontent.com/assets/411994/10662483/69ad1564-78b5-11e5-92bf-22440396fd26.png)

**Comment by karmeye** [comment] 2015-10-28 06:43
Things are looking good for iOS 9.2. (downloading)

https://twitter.com/catfish_man/status/659056930787164160

**Comment by grp** [comment] 2015-12-08 20:35
It looks like this should be fixed now: https://twitter.com/Catfish_Man/status/674287539574849536

**Closed by grp** 2015-12-08 20:35 UTC
