### ISSUE TITLE
I build the project  failed. error as follows.

### ISSUE THREAD

**Issue by starmier** [facebook/KVOController#68] opened 2015-06-24 08:46 UTC
Undefined symbols for architecture armv7s:
  "_llvm_gcov_init", referenced from:
      ___llvm_gcov_init in libFBKVOController.a(FBKVOController.o)
  "_llvm_gcda_end_file", referenced from:
      ___llvm_gcov_writeout in libFBKVOController.a(FBKVOController.o)
  "_llvm_gcda_emit_function", referenced from:
      ___llvm_gcov_writeout in libFBKVOController.a(FBKVOController.o)
  "_llvm_gcda_emit_arcs", referenced from:
      ___llvm_gcov_writeout in libFBKVOController.a(FBKVOController.o)
  "_llvm_gcda_start_file", referenced from:
      ___llvm_gcov_writeout in libFBKVOController.a(FBKVOController.o)
  "_llvm_gcda_summary_info", referenced from:
      ___llvm_gcov_writeout in libFBKVOController.a(FBKVOController.o)

then I try  to set  the option  OTHER LDFLAGS with the value of -fprofile-arcs -ftest-coverage ,and build success.
I want to konw if has other method  to sovle this error  all right?

**Comment by grp** [comment] 2015-06-24 23:18
@modocache, any ideas on this one?

**Comment by modocache** [comment] 2015-09-02 00:04
Thanks for reporting! :+1:

This is a duplicate of #65 -- closing this issue in favor of that one. Please follow along with that issue for updates.

**Closed** 2015-09-02 00:05 UTC
